### ISSUE TITLE
User icons

### ISSUE THREAD

**Issue by olivedae** [rprotasov/edsger#8]
I enjoy Github's random image generator (i'm sure there may be a library around which supports it) so it would be great if we can include that here. This default image will be saved when they create an account. Users can also add their own images if they would like.

Icons would be display as small squares/circles in various locations around the site.

We can follow Github's stye of uploading images at a later point after having icon support.

**Comment by rprotasov** [comment]
Actually, we can have a random image generator which creates smily face icons like Dropbox.

**Comment by ericvoorhis** [comment]
Added in aa62cc0ea48558d0bc62d287751a8685934516c3
